# Generated by Django 4.0.4 on 2022-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hamrobazaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulr', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
    ]
