# Generated by Django 4.0.4 on 2022-05-11 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamrobazaar',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='hamrobazaar',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamrobazaar',
            name='img',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hamrobazaar',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
