# Generated by Django 4.0.4 on 2022-05-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_hamrobazaar_mobile_number_hamrobazaar_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hamrobazaar',
            new_name='product',
        ),
    ]
